# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Project\KingOfEfficiency\ui\qtui\mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open_file = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_file.sizePolicy().hasHeightForWidth())
        self.btn_open_file.setSizePolicy(sizePolicy)
        self.btn_open_file.setObjectName("btn_open_file")
        self.horizontalLayout.addWidget(self.btn_open_file)
        self.label_db_path = QtWidgets.QLabel(self.centralwidget)
        self.label_db_path.setText("")
        self.label_db_path.setObjectName("label_db_path")
        self.horizontalLayout.addWidget(self.label_db_path)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_open_excel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_excel.sizePolicy().hasHeightForWidth())
        self.btn_open_excel.setSizePolicy(sizePolicy)
        self.btn_open_excel.setObjectName("btn_open_excel")
        self.horizontalLayout_3.addWidget(self.btn_open_excel)
        self.label_excel_path = QtWidgets.QLabel(self.centralwidget)
        self.label_excel_path.setText("")
        self.label_excel_path.setObjectName("label_excel_path")
        self.horizontalLayout_3.addWidget(self.label_excel_path)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_index = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_index.setObjectName("lineEdit_index")
        self.horizontalLayout_2.addWidget(self.lineEdit_index)
        self.btn_sreach = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sreach.setObjectName("btn_sreach")
        self.horizontalLayout_2.addWidget(self.btn_sreach)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_table = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_table.sizePolicy().hasHeightForWidth())
        self.listWidget_table.setSizePolicy(sizePolicy)
        self.listWidget_table.setObjectName("listWidget_table")
        self.horizontalLayout_4.addWidget(self.listWidget_table)
        self.tableView_main = QtWidgets.QTableView(self.centralwidget)
        self.tableView_main.setObjectName("tableView_main")
        self.horizontalLayout_4.addWidget(self.tableView_main)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "效率之王"))
        self.btn_open_file.setText(_translate("MainWindow", "打开数据库"))
        self.btn_open_excel.setText(_translate("MainWindow", "打开Excel"))
        self.btn_sreach.setText(_translate("MainWindow", "搜索"))
